baseURL = "localhost:1313"
languageCode = "en-US"
title = "STEAMConf 2019"
license = "GNU General Public License v3.0"
tags = "educacion, steam, education, steam"
tagline = "STEAMConf, 5th. International Education Conference"
description = "STEAMConf wants to visualize the vital importance of implementing programs and resources, which help to minimize the digital divide, gender imbalances and promote equal opportunities."
DefaultContentLanguage = "en"
copyright = "Â© STEAMConf 2019"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""


[languages]

  [languages.en]
    baseURL = "localhost:1313"
    title = "STEAMConf"
    weight = 1
    name = "EN"
    languageCode = "en-US"
  [languages.es]
    baseURL = "localhost:1313/es"
    title = "STEAMConf"
    weight = 2
    name = "ES"
    languageCode = "es-ES"
  [languages.ca]
    baseURL = "localhost:1313/ca"
    title = "STEAMConf"
    weight = 3
    name = "CA"
    languageCode = "ca-CA"
